/**
 * LLM-based claim filtering and verification
 * 
 * Uses an OpenAI-compatible API to assess whether text is a verifiable factual claim
 */

import axios from 'axios';
import { Claim, Verification, Rating } from '../types';

const OPENAI_API_BASE = 'https://api.openai.com/v1';

interface ClaimAnalysis {
  isVerifiableClaim: boolean;
  claimType: 'factual' | 'opinion' | 'prediction' | 'question' | 'command' | 'unknown';
  confidence: number;
  reasoning: string;
  suggestedRating?: Rating;
  suggestedSummary?: string;
}

/**
 * Analyze whether text represents a verifiable factual claim using LLM
 */
export async function analyzeClaimWithLLM(
  claim: Claim,
  apiKey: string
): Promise<ClaimAnalysis | null> {
  if (!apiKey) {
    return null;
  }
  
  try {
    const response = await axios.post(
      `${OPENAI_API_BASE}/chat/completions`,
      {
        model: 'gpt-4o-mini', // Cost-effective model for classification
        messages: [
          {
            role: 'system',
            content: `You are a fact-checking assistant. Analyze whether the given text is a verifiable factual claim.

A verifiable factual claim:
- Makes an assertion about objective reality that can be checked
- Contains specific details (numbers, names, events, dates)
- Is not purely opinion, prediction, or rhetorical question

Respond in JSON format:
{
  "isVerifiableClaim": boolean,
  "claimType": "factual" | "opinion" | "prediction" | "question" | "command" | "unknown",
  "confidence": 0.0-1.0,
  "reasoning": "Brief explanation"
}`
          },
          {
            role: 'user',
            content: `Analyze this text: "${claim.text}"`
          }
        ],
        temperature: 0.1,
        max_tokens: 200,
        response_format: { type: 'json_object' }
      },
      {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        timeout: 10000,
      }
    );
    
    const content = response.data.choices[0]?.message?.content;
    if (!content) return null;
    
    const analysis = JSON.parse(content) as ClaimAnalysis;
    console.log(`[LLMFilter] Claim "${claim.text.substring(0, 50)}..." -> ${analysis.isVerifiableClaim ? 'VERIFIABLE' : 'NOT VERIFIABLE'} (${analysis.claimType}, ${analysis.confidence})`);
    
    return analysis;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error('[LLMFilter] API error:', error.response?.status, error.response?.data?.error?.message);
    } else {
      console.error('[LLMFilter] Error:', error);
    }
    return null;
  }
}

/**
 * Use LLM to verify a claim when no fact-checks are found
 * This is a fallback for claims that haven't been formally fact-checked
 */
export async function verifyClaimWithLLM(
  claim: Claim,
  apiKey: string
): Promise<Verification | null> {
  if (!apiKey) {
    return null;
  }
  
  try {
    const response = await axios.post(
      `${OPENAI_API_BASE}/chat/completions`,
      {
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: `You are a fact-checking assistant. Analyze the given claim and provide a preliminary assessment.

IMPORTANT: 
- Be conservative - if unsure, say "unverified"
- Don't make up facts - only reference things you're confident about
- Note that AI assessments are less reliable than professional fact-checkers

Respond in JSON:
{
  "rating": "verified" | "mostly_true" | "mixed" | "mostly_false" | "false" | "unverified" | "opinion",
  "confidence": 0.0-1.0,
  "summary": "Brief explanation of the assessment",
  "caveats": ["Any important caveats or limitations"]
}`
          },
          {
            role: 'user',
            content: `Assess this claim: "${claim.text}"\n\nContext: Found on ${claim.sourceUrl || 'unknown source'}`
          }
        ],
        temperature: 0.2,
        max_tokens: 300,
        response_format: { type: 'json_object' }
      },
      {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        timeout: 15000,
      }
    );
    
    const content = response.data.choices[0]?.message?.content;
    if (!content) return null;
    
    const result = JSON.parse(content);
    
    // Add caveat that this is AI-generated
    const caveats = result.caveats || [];
    caveats.push('Assessment generated by AI - verify with authoritative sources');
    
    console.log(`[LLMVerify] Claim "${claim.text.substring(0, 50)}..." -> ${result.rating} (${result.confidence})`);
    
    return {
      claimId: claim.id,
      rating: result.rating as Rating,
      confidence: Math.min(result.confidence * 0.8, 0.7), // Cap confidence for AI-only verifications
      summary: result.summary,
      evidence: [{
        url: '',
        sourceName: 'AI Assessment (GPT-4)',
        quote: result.summary,
        peerReviewed: false,
      }],
      checkedAt: new Date().toISOString(),
      caveats,
    };
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error('[LLMVerify] API error:', error.response?.status, error.response?.data?.error?.message);
    } else {
      console.error('[LLMVerify] Error:', error);
    }
    return null;
  }
}

/**
 * Filter a batch of claims to only include verifiable ones
 */
export async function filterVerifiableClaims(
  claims: Claim[],
  apiKey: string
): Promise<Claim[]> {
  if (!apiKey) {
    console.log('[LLMFilter] No API key, skipping LLM filtering');
    return claims;
  }
  
  const verifiableClaims: Claim[] = [];
  
  for (const claim of claims) {
    const analysis = await analyzeClaimWithLLM(claim, apiKey);
    
    if (!analysis) {
      // If LLM fails, include the claim (fail open)
      verifiableClaims.push(claim);
      continue;
    }
    
    if (analysis.isVerifiableClaim && analysis.confidence >= 0.6) {
      verifiableClaims.push(claim);
    }
    
    // Small delay between LLM calls
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  
  console.log(`[LLMFilter] Filtered ${claims.length} claims to ${verifiableClaims.length} verifiable claims`);
  return verifiableClaims;
}
